language: python
python:
  # We don't actually use the Travis Python, but this keeps it organized.
  - "2.7"
  - "3.6"
install:
  - sudo apt-get update
  # Install Anaconda 
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  # Create conda environment
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION pytest numpy scipy matplotlib pandas plotly h5py numba
  - source activate test-environment
  - conda install -c astropy astroquery
  - pip install pytest-cov
  - python setup.py install

script:
  # Your test script goes here
  - echo ">>> Running tests"
  # use XVFB to have headless display port, and still run the Matplotlib tests.
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      xvfb-run pytest -m "not needs_db_CDSD_HITEMP and not python3_only" --cov=./;
    else
      xvfb-run pytest -m "not needs_db_CDSD_HITEMP and not python2_only" --cov=./;
    fi
  
# safelist
branches:
  only:
  - master
  - develop
  
 
after_success:
  # codecoverage for Python 3 only
  - if [[ "$TRAVIS_PYTHON_VERSION" != "2.7" ]]; then
      pip install codecov;
      codecov;
    fi