# See https://github.com/binder-examples/conda
name: radis-env
channels:
- conda-forge
- astropy
- cantera
- plotly
dependencies:
- python=3.8
- astropy>=4.3.1  # Unit aware calculations
- astroquery>=0.4.6  # to fetch HITRAN databases
- beautifulsoup4>=4.10.0 # parse ExoMol website
- cantera>=2.5.1   # for chemical equilibrium computations
- configparser
- cython          # EP : really needed? pipreqs doesn't say so
- habanero>=1.2.0  # CrossRef API to retrieve data from doi
- h5py>=3.2.1   # load HDF5
- joblib  # for parallel loading of SpecDatabase
- matplotlib
- numpy
- numba  # just-in-time compiler
- pandas>=1.0.5
- plotly>=2.5.1  # for line survey HTML output
- psutil # for getting user RAM
- pytables # for pandas to HDF5 export
- scipy>=1.4.0
- seaborn   # other matplotlib themes
- termcolor  # terminal colors
- specutils
- vaex-core>=4.17.0   # load HDF5 files  (version needed to fix https://github.com/radis/radis/issues/598)
- vaex-hdf5
- vaex-viz
- pip
- pip:
  - lxml           # parser used for ExoMol website
  - hjson          # Json with comments (for default_radis.json)
  - publib>=0.3.2  # Plotting styles for Matplotlib
  - hitran-api     # HAPI, used to access TIPS partition functions
  - peakutils
  - json-tricks>=3.15.0  # to deal with non jsonable formats
  - mpldatacursor
  - progressbar2    # used in vaex
  #- tuna           # to generate visual/interactive performance profiles
